### PR TITLE
236 feature documentation visionnode lidarnode

### PR DESCRIPTION
**Pull request by okrusch**
# Description

Documentation for Visione Node and Lidar Distance

Fixes # (236)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

## Does this PR introduce a breaking change?

NO

## Most important changes

Code and MarkDown Documentation of Perception elements

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (might be obsolete with CI later on)
- [ ] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Review by robertik10 — APPROVED** [review]
Looks Great!

**Comment by robertik10** [comment]
There seems to be just a little merge conflict regarding the file name, which needs to be changed to fit the numeration of the markdown perception files =)

**Comment by samuelkuehnel** [comment]
I resolved the merge conflict. Please cehck on your research and perception folder there seems to be old documentation for Efficient PS, old research from previous project and lidar distance utility

**Comment by robertik10** [comment]
> I resolved the merge conflict. Please cehck on your research and perception folder there seems to be old documentation for Efficient PS, old research from previous project and lidar distance utility

Should be fine I think, since he did not change or add anything to those files, they won't be in the final main branch when merging. At least I think so 🤔

**Pull request merged**
