### PR TITLE
110 - Implement traffic light detection

### LINKED ISSUE #110: [Feature]: Implementation of Traffic Light Detection
### Description

- [x] Adjust Vision Node to publish traffic lights
- [x] Create TLD node
- [x] Select correct traffic light -> maybe add 'side' class to only classify frontal facing traffic lights
- [x] Recognize correct traffic light state

### Definition of Done

_No response_

### PR DESCRIPTION
**Pull request by MaxJa4**
# Description

Extended the VisionNode to publish the cut out traffic lights and implemented a new traffic light detection node which uses them to recognize the traffic light state via a small neural network.

The node can publish the states UNKNOWN, GREEN, YELLOW, RED which are int8 enums as a ROS message.

The neural network has been extended to recognize side-facing traffic lights as a first measure of filtering those out. Additionally, a bounding box was laid over the source image, as the correct traffic light is towards the center of the image.

It was necessary to switch from 'yolov8x-seg' to yolo 'rtdetr-x' as the traffic lights were detected too late (had to be almost in the intersection to see them properly). Lack of segmentation wasn't an issue, cutting out by the bounding box of the recognized object was perfectly fine in this case.

Fixes #110

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Does this PR introduce a breaking change?

No

## Most important changes

- Extension of VisionNode
- Implementation of TrafficLightDetectionNode

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Review by JuliusMiller — APPROVED** [review]
Nice Implementation

**Review by okrusch — APPROVED** [review]
Nice work!

**Comment by okrusch** [comment]
Fix failed checks!

**Comment by MaxJa4** [comment]
Linter error fixed (came from main-branch).
Driving error not fixed, came from and still present in main-branch, reason unknown.

**Pull request merged**
