### PR TITLE
116 - Update CUDA in Dockerfile and bump requirement versions

### LINKED ISSUE #116: [Feature]: Update CUDA and Requirements to newest supported version
### Description

Update CUDA to 12.1 and Requirements to newest supported version to be able to use Torch 2.
Using a newest CUDA version and the newest Torch version should result in performance improvements and better VRAM management, possibly mitigating #102.

### Definition of Done

- Our project works with the new dependency versions
- Everything runs fine on the lab computers

### PR DESCRIPTION
**Pull request by MaxJa4**
# Description

Update CUDA in Dockerfile and bump requirement versions. See issue below for reasons why.

Fixes #116

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Does this PR introduce a breaking change?

No

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes (might be obsolete with CI later on)

### CODE REVIEW

**Comment by MaxJa4** [comment]
@okrusch You can use this branch to check whether #102 is fixed with this. Be aware that this now installs Torch 2.1.1 instead of 1.13.1

**Comment by samuelkuehnel** [comment]
image
I had an error when cloning the repo and running the command `b5 install`.

**Comment by samuelkuehnel** [comment]
Sorry for the bad screenshot, I will add a better one tomorrow.

**Comment by samuelkuehnel** [comment]
This one contains the whole error message: 
image

**Comment by MaxJa4** [comment]
@samuelkuehnel Thanks. I changed the installation method (which is also faster and simpler) for CUDA. Maybe that helps. Also removed libgit as it was a workaround for DVC and it seems to be fine without it now.

**Comment by samuelkuehnel** [comment]
The error seems to be on the PC as the git action that builds the image completes without an error. I still get an error when running `b5 install`.
image

@JuliusMiller also tried to run `b5 install` after cloning your branch and he sees the same error.

**Comment by MaxJa4** [comment]
> The error seems to be on the PC as the git action that builds the image completes without an error. I still get an error when running `b5 install`.
> 
> image
> 
> 
> 
> @JuliusMiller also tried to run `b5 install` after cloning your branch and he sees the same error.

Thanks for testing it. Hmm maybe the lab pcs need an `apt upgrade` as they may use an old kernel.
I'll try to find a workaround.
It also works for me on my machine (Ubuntu).

**Comment by MaxJa4** [comment]
Found a possible workaround for the error. Can you or @JuliusMiller try again? Thanks!

**Comment by samuelkuehnel** [comment]
Error sadly still exists :cry: 
image

**Comment by MaxJa4** [comment]
Did some more research, as there is no helpful error message anymore.
Turns out, that the lab pc graphics cards are too "old" for CUDA 12.X, so I downgraded to 11.8 (which still works with PyTorch 2).
Hope it works now. I won't be able to work on PAF tomorrow, so no hurry from my side :) Thanks!

**Comment by samuelkuehnel** [comment]
I tried the `b5 install`command again and it still fails :cry: 
image
I am in the laboratory today until 4:30 pm if you want me to test other solutions.

**Review by samuelkuehnel — APPROVED** [review]
Update works. Image is built and container starts as expected

**Pull request merged**
